# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies and build
COPY package.json package-lock.json tsconfig.json index.ts ./
RUN npm install --ignore-scripts && npm run build

# Expose nothing (stdio)

# Default command
CMD ["node", "dist/index.js"]
